// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const text: any = {
  languages: {
    PL: "Jenzyki",
    UA: "Мови",
    RU: "Языки",
    EN: "Languages",
  },
  login: {
    PL: "Zaloguise",
    UA: "Увiйти",
    RU: "Войти",
    EN: "Login",
  },
  note: {
    PL: "Notatka",
    UA: "Нотатка",
    RU: "Заметка",
    EN: "Note",
  },
  pinnedNote: {
    PL: "Załączona notatka",
    UA: "Прикріплена нотатка",
    RU: "Прикрепленная заметка",
    EN: "Pinned note",
  },
  quickNote: {
    PL: "Krótka notatka",
    UA: "Швидка нотатка",
    RU: "Быстрая заметка",
    EN: "Quick note",
  },
  newChapter: {
    PL: "Nowy rozdział",
    UA: "Новий роздiл",
    RU: "Новый раздел",
    EN: "New chapter",
  },
  installApp: {
    PL: "Zainstalować",
    UA: "Встановити додаток",
    RU: "Установить приложение",
    EN: "Install app",
  },
  enter: {
    PL: "Wejść",
    UA: "Увійти",
    RU: "Войти",
    EN: "Enter",
  },
  noUser: {
    PL: "Brak użytkownika",
    UA: "Немає користувача",
    RU: "Нет пользователя",
    EN: "No user",
  },
  noConnection: {
    PL: "Brak komunikacji",
    UA: "Немає зв'язку",
    RU: "Нет связи",
    EN: "No connection",
  },
  folderTitle: {
    PL: "Tytuł folderu",
    UA: "Назва папки",
    RU: "Название папки",
    EN: "Folder title",
  },
  chapterTitle: {
    PL: "Tytuł rozdziału",
    UA: "Назва розділу",
    RU: "Название раздела",
    EN: "Chapter title",
  },
  untitled: {
    PL: "Brak tytułu",
    UA: "Без назви",
    RU: "Без названия",
    EN: "Untitled",
  },
  articleTitle: {
    PL: "Tytuł artykułu",
    UA: "Назва статті",
    RU: "Название статьи",
    EN: "Article title",
  },
  newArticle: {
    PL: "Nowy artykuł",
    UA: "Нова стаття",
    RU: "Новая статья",
    EN: "New article",
  },
  newFolder: {
    PL: "Nowy folder",
    UA: "Нова папка",
    RU: "Новая папка",
    EN: "New folder",
  },
  transfer: {
    PL: "Przenieść",
    UA: "Перемістити",
    RU: "Переместить",
    EN: "Transfer",
  },
  chapter: {
    PL: "Rozdział",
    UA: "Розділ",
    RU: "Раздел",
    EN: "Chapter",
  },
  folders: {
    PL: "Przenieść",
    UA: "Папки",
    RU: "Папки",
    EN: "Folders",
  },
  delete: {
    PL: "Usunąć",
    UA: "Видалити",
    RU: "Удалить",
    EN: "Delete",
  },
  deleteUser: {
    PL: "Usunąć użyt-ka",
    UA: "Видалити кор-ча",
    RU: "Удалить польз-ля",
    EN: "Delete user",
  },
  exit: {
    PL: "Wyjście",
    UA: "Вихід",
    RU: "Выход",
    EN: "Exit",
  },
  restoreData: {
    PL: "Przywróć dane",
    UA: "Відновити дані",
    RU: "Восстановить данные",
    EN: "Restore data",
  },
  backup: {
    PL: "Kopia zapasowa",
    UA: "Резервна копія",
    RU: "Создать резервную копию",
    EN: "Backup",
  },
  textToCopy: {
    PL: "Tekst do skopiowania",
    UA: "Текст для копіювання",
    RU: "Текст для копирования",
    EN: "Text to copy",
  },
  todo: {
    PL: "Dodaj zadanie",
    UA: "Задача",
    RU: "Задача",
    EN: "Todo",
  },
  addTodo: {
    PL: "Zadania",
    UA: "Нова задача",
    RU: "Новая задача",
    EN: "New todo",
  },
  addCompletedTodos: {
    PL: "Usuwanie zakończone",
    UA: "Видалити виконане",
    RU: "Удалить выполненное",
    EN: "Delete completed",
  },
};
